### ISSUE TITLE
Tentando usar, mas não recebo retorno

### ISSUE THREAD

**Issue by LucasCFerraz** [pagseguro/pagseguro-android-sdk-checkout-in-app#1]
Pessoal, peço que me ajudem, estou tentando utilizar essa biblioteca, porém não recebi nenhum retorno da equipe do Pagseguro. Já implementei a solução no meu app porém ela não funciona, já que não tenho o acesso liberado.

Desde já agradeço!

**Comment by felipebranco** [comment]
@LucasCFerraz para ter acesso liberado para utilizar o Checkout in App:
O Checkout in App está operando em fase de piloto. Para fazer parte deste piloto você precisa seguir alguns passos:
Enviar um e-mail para checkoutinapp@pagseguro.com.br informando um telefone de contato e o e-mail da sua conta PagSeguro.
Se você for selecionado para o piloto, nossa equipe entrará em contato com você para obter mais informações e liberar a funcionalidade para a sua conta.
Implementar o Checkout in App em sua aplicação;Encaminhar os feedbacks para a nossa equipe. Nesta fase do projeto a sua opinião será extremamente importante.A equipe do PagSeguro dará todo o suporte para sua integração do Checkout in App com a sua aplicação.

**Comment by felipebranco** [comment]
@LucasCFerraz  para ter acesso liberado para utilizar o Checkout in App:
O Checkout in App está operando em fase de piloto. Para fazer parte deste piloto você precisa seguir alguns passos:
Enviar um e-mail para checkoutinapp@pagseguro.com.br informando um telefone de contato e o e-mail da sua conta PagSeguro.
Se você for selecionado para o piloto, nossa equipe entrará em contato com você para obter mais informações e liberar a funcionalidade para a sua conta.
Implementar o Checkout in App em sua aplicação;Encaminhar os feedbacks para a nossa equipe. Nesta fase do projeto a sua opinião será extremamente importante.A equipe do PagSeguro dará todo o suporte para sua integração do Checkout in App com a sua aplicação.
Qualquer dúvida segue documentação da Comunidade Pagseguro para consulta: https://dev.pagseguro.uol.com.br/documentacao/pagamento-online/aplicativo-pagseguro/checkout-in-app/checkout-in-app-android

**Comment by felipebranco** [comment]
@LucasCFerraz  para ter acesso liberado para utilizar o Checkout in App:
O Checkout in App está operando em fase de piloto. Para fazer parte deste piloto você precisa seguir alguns passos:
Enviar um e-mail para checkoutinapp@pagseguro.com.br informando um telefone de contato e o e-mail da sua conta PagSeguro.
Se você for selecionado para o piloto, nossa equipe entrará em contato com você para obter mais informações e liberar a funcionalidade para a sua conta.
Implementar o Checkout in App em sua aplicação;Encaminhar os feedbacks para a nossa equipe. Nesta fase do projeto a sua opinião será extremamente importante.A equipe do PagSeguro dará todo o suporte para sua integração do Checkout in App com a sua aplicação.
Qualquer dúvida segue documentação da Comunidade Pagseguro para consulta: https://dev.pagseguro.uol.com.br/documentacao/pagamento-online/aplicativo-pagseguro/checkout-in-app/checkout-in-app-android
